site_name: Linear 1.0 API
site_url: ""
use_directory_urls: false

nav:
  - Documenataion:
    - REST API Platform Overview: Documentation/rest-api-platform-overview-alt-1.md
    - Authentication: Documentation/rest-api-platform-overview-alt-1/authentication-validation-1.md
    - Getting Updates on Your Accounts: Documentation/rest-api-platform-overview-alt-1/getting-updates-on-your-submissions-booked-accounts.md
    - Line of Credit Functionality: Documentation/rest-api-platform-overview-alt-1/line-of-credit-functionality.md
    - Sandbox Integration and Testing: Documentation/rest-api-platform-overview-alt-1/sandbox-integration-and-testing.md
    - Submitting an Application: Documentation/rest-api-platform-overview-alt-1/submitting-an-application.md
  - Schema Explorer: /linear-v1/linear-api-v1-schema.html
theme: material
plugins: []

