site_name: Developer Docs - Linear 1.0 API
site_url: ""
use_directory_urls: false

nav:
  - Documenataion:
    - REST API Platform Overview: Documentation/rest-api-platform-overview-alt-1.md
    - Authentication: Documentation/rest-api-platform-overview-alt-1/authentication-validation-1.md
    - Getting Updates on Your Accounts: Documentation/rest-api-platform-overview-alt-1/getting-updates-on-your-submissions-booked-accounts.md
    - Line of Credit Functionality: Documentation/rest-api-platform-overview-alt-1/line-of-credit-functionality.md
    - Sandbox Integration and Testing: Documentation/rest-api-platform-overview-alt-1/sandbox-integration-and-testing.md
    - Submitting an Application: Documentation/rest-api-platform-overview-alt-1/submitting-an-application.md
  - Schema Explorer: /linear-v1/linear-api-v1-schema.html
  
theme: material
  icon:
    repo: fontawesome/brands/github
    logo: material/language-python
    
markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: true
  - toc:
      permalink: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

extra_css:
  - stylesheets/custom.css

